name: deploy

on:
  release:
    types: [created, edited]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Installs requirements
      run: |
        python -m pip install -r deploy-requirements.txt
    - name: Runs tests
      run: |
        python -m pytest --cov=cfinterface tests/
    - name: Static typing check
      run: |
        python -m mypy .
    - name: PEP8 check
      run: |
        python -m pylama --ignore E203 ./cfinterface
    - name: Installs dependencies
      if: startsWith(github.ref, 'refs/tags')
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
        python setup.py sdist bdist_wheel
    - name: PyPI publish
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
